### ISSUE TITLE
Timeline not initiating waypoint autoplay when accessed within story

### ISSUE THREAD

**Issue by jjkohler** [CMU-CREATE-Lab/data-visualization-tools#140]
Likely related to issue #139 

Waypoint/layer only loads and plays properly when accessed through direct # link.

https://staging.earthtime.org/explore#waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0&v=22.54581,24.27343,2.35,latLng&t=88.2&ps=50&l=bdrk,mmr&bt=20140131&et=20160630&startDwell=0&endDwell=0
![image](https://user-images.githubusercontent.com/42879120/94729634-f98c4d80-032f-11eb-8f36-2eaddf0cf417.png)
Here all behavior seems normal. Layer is loaded and begins to play as expected.

But when accessed manually within story or by story/waypoint link there is failure to initialize timeline. Timeline is displayed and shown to be in play position, but no playback begins until user manually interacts with timeline by dragging the scrub bar or pausing and playing again.
https://staging.earthtime.org/stories/top_50#waypointIdx=17&waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0
![image](https://user-images.githubusercontent.com/42879120/94729949-7ae3e000-0330-11eb-8d59-8dc75197c4aa.png)

**Comment by pdille** [comment]
This waypoint actually doesn't have a playback speed ('ps') encoded in the URL, which likely leads to unexpected behavior. It's possible we previously had some fail safe for this. I'll look, but I suspect just adding the 'ps' property to the share link will solve this. Who knows how many other waypoints are malformed like this though.

**Comment by pdille** [comment]
So the problem is twofold here.

1. The bt/et of this waypoint are beyond the time extents of this layer. What should happen is that you get the last frame. However, you'll see that while it is showing the last frame, the timeline is indicating the first frame. This is a timelapse library problem and has been corrected. That said, not sure where these bt/ets came from.

2. Since no 'ps' was part of the share link, the system assume a default playback speed. However, because the bt/et are the same (because it is capping at the max duration) the system is trying to loop on the same frame, hence why the playback UI button is indicating that it is playing.  Perhaps there should be a check in the system that if someone does modify a share link to have the same bt/et but not be paused, the system automatically pauses.

**Comment by pdille** [comment]
To add to this, the bt/et are indeed bad. Looking back at the original waypoint (from the Default sheet), the formula to generate it (and similar ones) was malformed. I've restored the previous values.

**Comment by jjkohler** [comment]
Different links now all produce same, correct results!

**Comment by jjkohler** [comment]
@pdille "Perhaps there should be a check in the system that if someone does modify a share link to have the same bt/et but not be paused, the system automatically pauses." Is this a feature suggestion?
