### ISSUE TITLE
Boundary Legend Missing

### ISSUE THREAD

**Issue by jjkohler** [CMU-CREATE-Lab/data-visualization-tools#169]
![image](https://user-images.githubusercontent.com/42879120/97446040-50bc1880-1904-11eb-9c1f-5f8e74e40eab.png)
https://golden.earthtime.org/explore#waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0&v=40.43858,-79.8769,8.56,latLng&t=0.13&ps=50&l=bdrk_detailed,voting_ac_us_house_boundaries_2018,bdrk,voting_ac_polling_places_2018&bt=20180101&et=20201231&startDwell=0&endDwell=0

Staging:
![image](https://user-images.githubusercontent.com/42879120/97446087-5fa2cb00-1904-11eb-9d31-b96b1fe59e41.png)
https://staging.earthtime.org/explore#waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0&v=40.43858,-79.8769,8.559,latLng&t=0.17&ps=50&l=bdrk,bdrk_detailed,voting_ac_us_house_boundaries_2018,voting_ac_polling_places_2018&bt=20180101&et=20201231&startDwell=0&endDwell=0

**Comment by pdille** [comment]
Should be fixed in commit 08ec67f7ae Please confirm

Note that it will be worth checking layers that only have a title and credit (or perhaps even no credit). We may not want some of these layers to actually show a legend, which can be handled by setting 'Legend Content' to "none" in the spreadsheet.

**Comment by jjkohler** [comment]
This issue appears to have been fixed.
