### ISSUE TITLE
Split (paired) Circles Not Showing per Expectations

### ISSUE THREAD

**Issue by jjkohler** [CMU-CREATE-Lab/data-visualization-tools#176]
![image](https://user-images.githubusercontent.com/42879120/99717214-1e22bd00-2a77-11eb-9b1b-6c953e04090f.png)
https://golden.earthtime.org/explore#v=40.45683,-79.97422,9.029,latLng&t=3.16&ps=0&l=bdrk_subtle,allegheny_county_outline,allegheny_county_pgh,allegheny_school_aiu_catch_hs,allegheny_school_pps_catch_hs,allegheny_school_black_enroll_charter_paired,allegheny_school_white_enroll_charter_paired&bt=20160101&et=20160101

![image](https://user-images.githubusercontent.com/42879120/99717238-2975e880-2a77-11eb-9489-ff92176d93ad.png)
https://staging.earthtime.org/explore#v=40.45683,-79.97422,9.029,latLng&t=3.16&ps=0&l=bdrk_subtle,allegheny_county_outline,allegheny_county_pgh,allegheny_school_aiu_catch_hs,allegheny_school_pps_catch_hs,allegheny_school_black_enroll_charter_paired,allegheny_school_white_enroll_charter_paired&bt=20160101&et=20160101

**Comment by pdille** [comment]
Note that these are the subset of layers that make use of "_paired" in their ids

**Comment by rsargent** [comment]
Fixed in 36c14d6a7ce378203864df133579f8de3207b63b

Tested using a collection of paired visualizations currently in use: 
 https://staging.earthtime.org/stories/paired_layers#waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0 and https://golden.earthtime.org/stories/paired_layers#waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0

We thought we could modify individual _paired layers to use drawing mode 2 or 3 to hardcode to left or right half circle, but the extant usage mixed and matched such that sometimes _paired layers are on the left and sometimes on the right.
