### ISSUE TITLE
Some layers don't get default draw order at creation

### ISSUE THREAD

**Issue by jjkohler** [CMU-CREATE-Lab/data-visualization-tools#187]
![image](https://user-images.githubusercontent.com/42879120/100896838-0d1d7700-348d-11eb-960c-e2ce30c9efbe.png)

Census dotmap layers currently have no assigned draw order, so if base layers occur in the link after the dotmap layer, the dotmaps become invisible. 

550 is the current proposed draw order for census dotmaps.

An example of the incorrect behavior can be seen here:
https://staging.earthtime.org/explore#waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0&v=40.39988,-79.92097,9.193,latLng&t=0.03&ps=50&l=bdrk,acs2016_work_young_males,bdrk_detailed&bt=20180101&et=20181231&startDwell=0&endDwell=0

**Comment by rsargent** [comment]
Census dotmaps are an example.
Some outline layers, e.g. school district outlines are another example.

**Comment by rsargent** [comment]
As of c9d53695efa73ccdf3d35873702485c91185590c, All layers now receive a drawing order, according to the following recipe:

If 'Draw Order' specified in spreadsheet, use that, otherwise:
Category 'Base Maps': 100
Map type raster, raster2, timemachine: 200
Map type choropleth: 400
Map type dotmap: 550
Map type vector, bubble: 600
All others: 400

The design doc https://docs.google.com/document/d/1uesUk8OaWr4yQAXfuvgVMJGEY0Cr9q3gCrFy6sfqOxg/edit#heading=h.5rjrxfchcuyr
 also specifies Dot flows (e.g. refugees) as 700.  These are type='vector', so let's override them in the spreadsheets.  (Added as #188)
