### ISSUE TITLE
MapType=point layer does not display if it is earlier in the list of layers than MapType=polygon

### ISSUE THREAD

**Issue by rsargent** [CMU-CREATE-Lab/data-visualization-tools#246]
To reproduce, go to

https://earthtime.org/#csvlayers=11t8XP5yipm-8aceGU-wcr-qIjg-kFTASY1IZVoQ8M4Q.1706635433&waypoints=11t8XP5yipm-8aceGU-wcr-qIjg-kFTASY1IZVoQ8M4Q.0&theme=anne_test&story=anne_choropleth_test

and click on 3rd waypoint, observing green parcel dots do appear:
<img width="663" alt="image" src="https://user-images.githubusercontent.com/324851/156569240-ab1267ad-33ab-4e8d-a865-2bd00c7235a6.png">

Click on 4th waypoint, observing green parcel dots no longer appear:
<img width="650" alt="image" src="https://user-images.githubusercontent.com/324851/156569375-e01b2daf-d16f-45ec-a47b-ebac189ad141.png">

Both waypoints have same layers, just in different order.  Note that the problem isn't related to the choropleth obscuring the green dots;  the green dots disappear everywhere, including places they are not behind the choropleth.

**Comment by pdille** [comment]
Something first to note is that green dot layer (allegheny_county_oo_parcels_by_pct_black_hh_80_pct_plus_in_purchase_year) doesn't have data for 2022. You can see that [in action here](https://earthtime.org/explore#v=40.46517,-79.92662,10.09,latLng&t=0.33&ps=50&l=bdrk_detailed,allegheny_county_oo_parcels_by_pct_black_hh_80_pct_plus_in_purchase_year&bt=20100101&et=20220101)

Now the reason there is no timeline when the layers are in the order of the 4th waypoint is because the choropleth layer is defined to only span a single year and because the timeline that is shown is based on the last layer in the share link, the choropleth layer's timeline is used. And because start/end year is the same, no time line appears. Now because internally it has set the display year to 2022 (based on this 'hidden single year timeline'), going back to the first issue that the green dots don't have data for 2022 we end up no longer seeing them.

**Comment by gabrielo** [comment]
A possible solution is to not specify a start/end date for the choropleth. This would make it always on regardless of other layers' times and allow the time bounds associated with the dots to take precedence.

**Comment by rsargent** [comment]
Confirmed Paul and Gabriel, removing the dates from the choropleth did indeed fix this.  Thanks both!
