### ISSUE TITLE
Scrolling story uses landscape images/videos inside vertically-oriented div for non-mobile

### ISSUE THREAD

**Issue by rsargent** [CMU-CREATE-Lab/data-visualization-tools#39]

**Comment by chrisbartley** [comment]
Yep, on desktop it'll currently always use landscape because it only chooses/toggles between portrait/landscape based on the `window.orientation` property and the `orientationchange` event, neither of which are available on desktop.  So the code simply defaults to landscape when `window.orientation` is undefined[1].  An easyish fix would be to check window dimensions on initial load when `window.orientation` is undefined and to also listen to resize events to swap landscape/portrait as appropriate if the user resizes the browser.

[1] https://github.com/CMU-CREATE-Lab/data-visualization-tools/blob/master/examples/webgl-timemachine/stories/mobile-embed.js#L67

**Comment by pdille** [comment]
Looks like this was resolved some time ago. Closing thread, but please reopen if behavior isn't as expected.
