### ISSUE TITLE
Years at the bottom of scrolling stories have issues

### ISSUE THREAD

**Issue by arwright** [CMU-CREATE-Lab/data-visualization-tools#82]
Examples: [CHR scrolling story](https://earthtime.org/m/stories/chr#waypoints=1rCiksJv4aXi1usI0_9zdl4v5vuOfiHgMRidiDPt1WfE.1073081657)

First waypoint has bt=20160101&et=20160101 and should show 2016, but shows 2015:
![image](https://user-images.githubusercontent.com/449922/61377510-5d347300-a871-11e9-8407-1750ea68f70a.png)

Tenth waypoint has bt=19370101&et=19370101 and should show 1937, but shows 1984:

![image](https://user-images.githubusercontent.com/449922/61377300-eeefb080-a870-11e9-820f-4d3d245b3b1d.png)

**Comment by pdille** [comment]
I think this story may have changed some since the initial reporting of this?

That said, if I [re-run the first waypoint](https://thumbnails-v2.createlab.org/thumbnail?root=https://headless.earthtime.org/%23v%3D40.42129%2C-79.93609%2C10.248%2ClatLng%26bt%3D20160101%26et%3D20160101%26t%3D0.0%26ps%3D0%26l%3Dbdrk_detailed%2Callegheny_county_pgh%2Cacs2016_renter_w_children&width=1280&height=720&format=jpg&fps=30&tileFormat=mp4&fromScreenshot&timestampOnlyUI=true&redo=1), I get output that looks like this, which shows 2016.

For the 10th waypoint, a question I have is the data (pa_redlining_pgh_choropleth) is defined as having a single year, 2018. Did it used to cover multiple years? If I [re-run this waypoint](https://thumbnails-v2.createlab.org/thumbnail?root=https://headless.earthtime.org/%23v%3D40.42129%2C-79.93609%2C10.248%2ClatLng%26t%3D0%26ps%3D0%26l%3Dbdrk_detailed%2Cbdrk%2Callegheny_county_pgh%2Cpa_redlining_pgh_choropleth%26bt%3D19370101%26et%3D19370101%26startDwell%3D0%26endDwell%3D0&width=1280&height=720&format=jpg&fps=30&tileFormat=mp4&fromScreenshot&timestampOnlyUI=true&redo=2) then I get output that shows 2018. Note that there was an issue that would cause it to display the wrong year but that has since been fixed. That now seems to be independent of this layer though.

**Comment by rsargent** [comment]
@arwright can you take a look and confirm whether bug continues to exist or is fixed?

**Comment by pdille** [comment]
Ping on this. @arwright

**Comment by arwright** [comment]
Sorry for the delay.  I didn't realize it at the time, but there are actually two issues.  One is fixed.  One is still an issue.

The 1937 waypoint is now happy.  Thank you very much for that.

[Here is a new test.](https://earthtime.org/m/stories/scrolling_story_time_issue#waypoints=1rCiksJv4aXi1usI0_9zdl4v5vuOfiHgMRidiDPt1WfE.1073081657)

The first waypoint has bt=20160101&et=20160101 and shows 2015 at the bottom.

The second has bt=20160102&et=20160102 and shows 2016.

I think this is a manifestation of an issue with the semantics of time zones.  I would argue that the time you give in the timestamps/bt/et is the time you want to see reflected in the visuals and controls.  The actual behavior seems, I think, to be treating it as if I want to see the local time when the GMT time was the time in the timestamp/bt/et.  

This particularly causes problems in doing animations at the scale of days.  It seems likely that the year at the bottom of the scrolling story could also be similarly affected, so 201601010 -> 20151231 due to timezones and prints the 2015.  

I know this is a bigger discussion than this bug.  Sorry.

**Comment by arwright** [comment]
No.  Sorry.  User error.  I forgot about cacheing and misinterpreted what I saw.  This all works now.
