### ISSUE TITLE
Sea Level Rise timelines sometimes show 1984-2016 instead of temperature

### ISSUE THREAD

**Issue by rsargent** [CMU-CREATE-Lab/data-visualization-tools#93]
To reproduce, visit

https://earthtime.org/stories/internallayers#waypoints=1dxJ2YR3MFYTyZrV3MiGsm7kbOGPdvlzHL0_8HXhT7Bo.1596808134

and then click next waypoint (slr15, or page-up).  Timeline will show 1984-2016 instead of temperature

![image](https://user-images.githubusercontent.com/324851/66389016-58292080-e995-11e9-9112-ccd427c60182.png)

**Comment by rsargent** [comment]
Reproduced during presentations in Jan.

**Comment by pdille** [comment]
Fixed in commit 76b92a8e26d Please confirm.

Technically if a base layer was included in those waypoint share links this likely would not have happened. A normal share link always includes a base layer. That said, this edge case is now handled. Eventual timeline refactor will also solve issues like this.

**Comment by rsargent** [comment]
Confirmed fixed!  Tested at earthtime.org
